#!/usr/bin/python

import sys
import logging
import threading

from utils import *
from cmdline import *
from network import *

# ------------------------------------------------------------------------
# --- MAIN ---------------------------------------------------------------
# ------------------------------------------------------------------------

FORMAT = '%(asctime)-15s %(levelname)-7s [%(threadName)-10s] (%(module)s::%(funcName)s) [L:%(lineno)d] %(message)s'
logging.basicConfig(format=FORMAT, filename="cbpx.log")
l = logging.getLogger('cbpx')
l.setLevel(logging.INFO)

l.info("Startup")

try:
    cfg = parse_cmdline()
    backends = [{"ip":cfg.active_ip, "port":cfg.active_port}, {"ip":cfg.standby_ip, "port":cfg.standby_port}]
except Exception, e:
    print "Error parsing command line: " + str(e)
    sys.exit(1)

conn = cbpx_listener(cfg.port, backends)
flush = cbpx_flusher()

conn.start()
flush.start()

print_logo()
print_cfg(cfg)

l.info("Entering commandline loop")

while True:
    if process_command(): break

conn.close()
conn.join()

do_flush.set()
flush.close()
flush.join()

print " Bye."

l.info("Exiting")

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
