#!/bin/bash

REPO=/home/amo/projekty/cbpx-git
VERSION=$1

if [ -z "$VERSION" ] ; then
	echo "use: $0 branch"
	exit 1
fi

git clone $REPO -b $VERSION cbpx-$VERSION
rm -rf cbpx-$VERSION/.git
rm -f cbpx-$VERSION/cbpx-release
rm -f cbpx-$VERSION/naparzacz
rm -f cbpx-$VERSION/cbpx_threads.dia
sed -i s/__cbpx__version__/$VERSION/g cbpx-$VERSION/utils.py
sed -i s/l.debug/#l.debug/g cbpx-$VERSION/*.py
tar czf cbpx-$VERSION.tar.gz cbpx-$VERSION
